# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: './build.ps1 --bootstrap'
    
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: './build.ps1 -target=TransformConfigs -Ambiente="PROD"'

- script: dotnet build ./DemoCake.sln --configuration $(buildConfiguration)
  displayName: 'Compila o Projeto'

- script: dotnet publish ./DemoCake.sln --configuration $(buildConfiguration)
  displayName: 'Publica o Projeto'

- task: PublishPipelineArtifact@0
  displayName: Publica os Artefatos
  inputs:
    artifactName: 'artifact'
    targetPath: 'DemoCake/bin/Release/netcoreapp2.2/publish '